
import type { Metadata } from "next";
import MenuPayrollManagement from "@/components/payroll/MenuPayrollManagement";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function MainLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div className="h-screen mt-5 p-10">
      <div className="mb-10">
        <h1 className="text-4xl font-bold">Payroll Management</h1>
        <hr
          style={{
            background: "black",
            color: "lime",
            borderColor: "black",
            height: "3px",
            width: "450px",
          }}
        />
      </div>
      <MenuPayrollManagement/>

      <main className="grow ">{children}</main>

    </div>
  );
}
